/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CarSales;

/**
 *
 * @author aksha
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form AddCar
     */
    public Admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        logout_label = new javax.swing.JPanel();
        logout_textfield = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        cars_panel_5 = new javax.swing.JPanel();
        cars_panel_2_icon3 = new javax.swing.JLabel();
        cars_panel_2_name3 = new javax.swing.JLabel();
        cars_panel_2_company_name3 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        cars_panel_2_buy3 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        cars_panel_2_view_more = new javax.swing.JLabel();
        cars_panel_10 = new javax.swing.JPanel();
        cars_panel_2_icon8 = new javax.swing.JLabel();
        cars_panel_2_name8 = new javax.swing.JLabel();
        cars_panel_2_company_name8 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        cars_panel_2_buy8 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        cars_panel_2_view_more1 = new javax.swing.JLabel();
        cars_panel_11 = new javax.swing.JPanel();
        cars_panel_2_icon9 = new javax.swing.JLabel();
        cars_panel_2_name9 = new javax.swing.JLabel();
        cars_panel_2_company_name9 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        cars_panel_2_buy9 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        cars_panel_2_view_more2 = new javax.swing.JLabel();
        cars_panel_12 = new javax.swing.JPanel();
        cars_panel_2_icon10 = new javax.swing.JLabel();
        cars_panel_2_name10 = new javax.swing.JLabel();
        cars_panel_2_company_name10 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        cars_panel_2_buy10 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        cars_panel_2_view_more3 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        prev_page_panel1 = new javax.swing.JPanel();
        prev_page_icon1 = new javax.swing.JLabel();
        next_page_panel1 = new javax.swing.JPanel();
        next_page_icon1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(58, 56, 77));
        jPanel3.setPreferredSize(new java.awt.Dimension(800, 440));

        jPanel4.setBackground(new java.awt.Color(38, 40, 55));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Orders");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Recent purchases");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("User");

        logout_label.setBackground(new java.awt.Color(38, 40, 55));
        logout_label.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(242, 109, 125), 1, true));
        logout_label.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logout_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logout_labelMouseClicked(evt);
            }
        });

        logout_textfield.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        logout_textfield.setForeground(new java.awt.Color(255, 255, 255));
        logout_textfield.setText("Logout");
        logout_textfield.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logout_textfield.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logout_textfieldMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout logout_labelLayout = new javax.swing.GroupLayout(logout_label);
        logout_label.setLayout(logout_labelLayout);
        logout_labelLayout.setHorizontalGroup(
            logout_labelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logout_labelLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(logout_textfield)
                .addContainerGap(80, Short.MAX_VALUE))
        );
        logout_labelLayout.setVerticalGroup(
            logout_labelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logout_labelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logout_textfield, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logout_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(146, 146, 146)
                .addComponent(logout_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(77, 77, 77))
        );

        jPanel5.setBackground(new java.awt.Color(58, 56, 77));

        cars_panel_5.setBackground(new java.awt.Color(58, 56, 77));
        cars_panel_5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(94, 237, 181), 1, true));

        cars_panel_2_icon3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CarSales/assets/icons/car-jeep.png"))); // NOI18N

        cars_panel_2_name3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cars_panel_2_name3.setForeground(new java.awt.Color(255, 255, 255));
        cars_panel_2_name3.setText("Single Car Name");

        cars_panel_2_company_name3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cars_panel_2_company_name3.setForeground(new java.awt.Color(255, 255, 255));
        cars_panel_2_company_name3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        cars_panel_2_company_name3.setText("(Company Name)");

        jPanel9.setBackground(new java.awt.Color(58, 56, 77));

        cars_panel_2_buy3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CarSales/assets/icons/online-shopping -32.png"))); // NOI18N
        cars_panel_2_buy3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cars_panel_2_buy3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cars_panel_2_buy3, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
        );

        jPanel10.setBackground(new java.awt.Color(58, 56, 77));

        cars_panel_2_view_more.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CarSales/assets/icons/more.png"))); // NOI18N
        cars_panel_2_view_more.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cars_panel_2_view_more, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cars_panel_2_view_more, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout cars_panel_5Layout = new javax.swing.GroupLayout(cars_panel_5);
        cars_panel_5.setLayout(cars_panel_5Layout);
        cars_panel_5Layout.setHorizontalGroup(
            cars_panel_5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cars_panel_5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cars_panel_2_icon3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(cars_panel_5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cars_panel_2_name3, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cars_panel_2_company_name3, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 158, Short.MAX_VALUE)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        cars_panel_5Layout.setVerticalGroup(
            cars_panel_5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cars_panel_2_icon3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(cars_panel_5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cars_panel_5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cars_panel_5Layout.createSequentialGroup()
                        .addComponent(cars_panel_2_name3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cars_panel_2_company_name3))
                    .addGroup(cars_panel_5Layout.createSequentialGroup()
                        .addGroup(cars_panel_5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        cars_panel_10.setBackground(new java.awt.Color(58, 56, 77));
        cars_panel_10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(94, 237, 181), 1, true));

        cars_panel_2_icon8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CarSales/assets/icons/car-jeep.png"))); // NOI18N

        cars_panel_2_name8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cars_panel_2_name8.setForeground(new java.awt.Color(255, 255, 255));
        cars_panel_2_name8.setText("User Name");

        cars_panel_2_company_name8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cars_panel_2_company_name8.setForeground(new java.awt.Color(255, 255, 255));
        cars_panel_2_company_name8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        cars_panel_2_company_name8.setText("Car Name");

        jPanel12.setBackground(new java.awt.Color(58, 56, 77));

        cars_panel_2_buy8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CarSales/assets/icons/online-shopping -32.png"))); // NOI18N
        cars_panel_2_buy8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cars_panel_2_buy8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cars_panel_2_buy8, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
        );

        jPanel16.setBackground(new java.awt.Color(58, 56, 77));

        cars_panel_2_view_more1.setText("date");
        cars_panel_2_view_more1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(cars_panel_2_view_more1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cars_panel_2_view_more1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout cars_panel_10Layout = new javax.swing.GroupLayout(cars_panel_10);
        cars_panel_10.setLayout(cars_panel_10Layout);
        cars_panel_10Layout.setHorizontalGroup(
            cars_panel_10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cars_panel_10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cars_panel_2_icon8, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cars_panel_2_name8, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(cars_panel_2_company_name8, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        cars_panel_10Layout.setVerticalGroup(
            cars_panel_10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cars_panel_2_icon8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(cars_panel_10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cars_panel_10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cars_panel_10Layout.createSequentialGroup()
                        .addGroup(cars_panel_10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cars_panel_10Layout.createSequentialGroup()
                        .addGap(0, 9, Short.MAX_VALUE)
                        .addGroup(cars_panel_10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cars_panel_2_name8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cars_panel_2_company_name8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        cars_panel_11.setBackground(new java.awt.Color(58, 56, 77));
        cars_panel_11.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(94, 237, 181), 1, true));

        cars_panel_2_icon9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CarSales/assets/icons/car-jeep.png"))); // NOI18N

        cars_panel_2_name9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cars_panel_2_name9.setForeground(new java.awt.Color(255, 255, 255));
        cars_panel_2_name9.setText("Single Car Name");

        cars_panel_2_company_name9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cars_panel_2_company_name9.setForeground(new java.awt.Color(255, 255, 255));
        cars_panel_2_company_name9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        cars_panel_2_company_name9.setText("(Company Name)");

        jPanel17.setBackground(new java.awt.Color(58, 56, 77));

        cars_panel_2_buy9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CarSales/assets/icons/online-shopping -32.png"))); // NOI18N
        cars_panel_2_buy9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cars_panel_2_buy9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cars_panel_2_buy9, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
        );

        jPanel18.setBackground(new java.awt.Color(58, 56, 77));

        cars_panel_2_view_more2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CarSales/assets/icons/more.png"))); // NOI18N
        cars_panel_2_view_more2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cars_panel_2_view_more2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cars_panel_2_view_more2, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout cars_panel_11Layout = new javax.swing.GroupLayout(cars_panel_11);
        cars_panel_11.setLayout(cars_panel_11Layout);
        cars_panel_11Layout.setHorizontalGroup(
            cars_panel_11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cars_panel_11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cars_panel_2_icon9, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(cars_panel_11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cars_panel_2_name9, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cars_panel_2_company_name9, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 158, Short.MAX_VALUE)
                .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        cars_panel_11Layout.setVerticalGroup(
            cars_panel_11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cars_panel_2_icon9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(cars_panel_11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cars_panel_11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cars_panel_11Layout.createSequentialGroup()
                        .addComponent(cars_panel_2_name9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cars_panel_2_company_name9))
                    .addGroup(cars_panel_11Layout.createSequentialGroup()
                        .addGroup(cars_panel_11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        cars_panel_12.setBackground(new java.awt.Color(58, 56, 77));
        cars_panel_12.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(94, 237, 181), 1, true));

        cars_panel_2_icon10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CarSales/assets/icons/car-jeep.png"))); // NOI18N

        cars_panel_2_name10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cars_panel_2_name10.setForeground(new java.awt.Color(255, 255, 255));
        cars_panel_2_name10.setText("Single Car Name");

        cars_panel_2_company_name10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cars_panel_2_company_name10.setForeground(new java.awt.Color(255, 255, 255));
        cars_panel_2_company_name10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        cars_panel_2_company_name10.setText("(Company Name)");

        jPanel19.setBackground(new java.awt.Color(58, 56, 77));

        cars_panel_2_buy10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CarSales/assets/icons/online-shopping -32.png"))); // NOI18N
        cars_panel_2_buy10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cars_panel_2_buy10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cars_panel_2_buy10, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
        );

        jPanel20.setBackground(new java.awt.Color(58, 56, 77));

        cars_panel_2_view_more3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CarSales/assets/icons/more.png"))); // NOI18N
        cars_panel_2_view_more3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cars_panel_2_view_more3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cars_panel_2_view_more3, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout cars_panel_12Layout = new javax.swing.GroupLayout(cars_panel_12);
        cars_panel_12.setLayout(cars_panel_12Layout);
        cars_panel_12Layout.setHorizontalGroup(
            cars_panel_12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cars_panel_12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cars_panel_2_icon10, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(cars_panel_12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cars_panel_2_name10, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cars_panel_2_company_name10, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 158, Short.MAX_VALUE)
                .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        cars_panel_12Layout.setVerticalGroup(
            cars_panel_12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cars_panel_2_icon10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(cars_panel_12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cars_panel_12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cars_panel_12Layout.createSequentialGroup()
                        .addComponent(cars_panel_2_name10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cars_panel_2_company_name10))
                    .addGroup(cars_panel_12Layout.createSequentialGroup()
                        .addGroup(cars_panel_12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel21.setBackground(new java.awt.Color(58, 56, 77));
        jPanel21.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(94, 237, 181), 1, true));

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 632, Short.MAX_VALUE)
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 72, Short.MAX_VALUE)
        );

        jPanel22.setBackground(new java.awt.Color(58, 56, 77));
        jPanel22.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(94, 237, 181), 1, true));

        prev_page_panel1.setBackground(new java.awt.Color(58, 56, 77));
        prev_page_panel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        prev_page_panel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                prev_page_panel1MouseClicked(evt);
            }
        });

        prev_page_icon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CarSales/assets/icons/left-chevron.png"))); // NOI18N
        prev_page_icon1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                prev_page_icon1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout prev_page_panel1Layout = new javax.swing.GroupLayout(prev_page_panel1);
        prev_page_panel1.setLayout(prev_page_panel1Layout);
        prev_page_panel1Layout.setHorizontalGroup(
            prev_page_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(prev_page_panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(prev_page_icon1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        prev_page_panel1Layout.setVerticalGroup(
            prev_page_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(prev_page_icon1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        next_page_panel1.setBackground(new java.awt.Color(58, 56, 77));
        next_page_panel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        next_page_panel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                next_page_panel1MouseClicked(evt);
            }
        });

        next_page_icon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CarSales/assets/icons/right-chevron.png"))); // NOI18N
        next_page_icon1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                next_page_icon1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout next_page_panel1Layout = new javax.swing.GroupLayout(next_page_panel1);
        next_page_panel1.setLayout(next_page_panel1Layout);
        next_page_panel1Layout.setHorizontalGroup(
            next_page_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, next_page_panel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(next_page_icon1)
                .addContainerGap())
        );
        next_page_panel1Layout.setVerticalGroup(
            next_page_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(next_page_icon1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel22Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(prev_page_panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(next_page_panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel22Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(next_page_panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(prev_page_panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cars_panel_5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cars_panel_11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cars_panel_12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(cars_panel_10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(cars_panel_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cars_panel_11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cars_panel_12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(jPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(cars_panel_10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(454, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 876, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 548, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logout_textfieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout_textfieldMouseClicked
        // TODO add your handling code here:
        Home h = new Home();
        h.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logout_textfieldMouseClicked

    private void logout_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout_labelMouseClicked
        // TODO add your handling code here:
        Home h = new Home();
        h.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_logout_labelMouseClicked

    private void prev_page_panel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prev_page_panel1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_prev_page_panel1MouseClicked

    private void next_page_icon1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_next_page_icon1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_next_page_icon1MouseClicked

    private void next_page_panel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_next_page_panel1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_next_page_panel1MouseClicked

    private void prev_page_icon1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prev_page_icon1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_prev_page_icon1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cars_panel_10;
    private javax.swing.JPanel cars_panel_11;
    private javax.swing.JPanel cars_panel_12;
    private javax.swing.JPanel cars_panel_2;
    private javax.swing.JLabel cars_panel_2_buy;
    private javax.swing.JLabel cars_panel_2_buy1;
    private javax.swing.JLabel cars_panel_2_buy10;
    private javax.swing.JLabel cars_panel_2_buy2;
    private javax.swing.JLabel cars_panel_2_buy3;
    private javax.swing.JLabel cars_panel_2_buy4;
    private javax.swing.JLabel cars_panel_2_buy5;
    private javax.swing.JLabel cars_panel_2_buy6;
    private javax.swing.JLabel cars_panel_2_buy7;
    private javax.swing.JLabel cars_panel_2_buy8;
    private javax.swing.JLabel cars_panel_2_buy9;
    private javax.swing.JLabel cars_panel_2_company_name;
    private javax.swing.JLabel cars_panel_2_company_name1;
    private javax.swing.JLabel cars_panel_2_company_name10;
    private javax.swing.JLabel cars_panel_2_company_name2;
    private javax.swing.JLabel cars_panel_2_company_name3;
    private javax.swing.JLabel cars_panel_2_company_name4;
    private javax.swing.JLabel cars_panel_2_company_name5;
    private javax.swing.JLabel cars_panel_2_company_name6;
    private javax.swing.JLabel cars_panel_2_company_name7;
    private javax.swing.JLabel cars_panel_2_company_name8;
    private javax.swing.JLabel cars_panel_2_company_name9;
    private javax.swing.JLabel cars_panel_2_icon;
    private javax.swing.JLabel cars_panel_2_icon1;
    private javax.swing.JLabel cars_panel_2_icon10;
    private javax.swing.JLabel cars_panel_2_icon2;
    private javax.swing.JLabel cars_panel_2_icon3;
    private javax.swing.JLabel cars_panel_2_icon4;
    private javax.swing.JLabel cars_panel_2_icon5;
    private javax.swing.JLabel cars_panel_2_icon6;
    private javax.swing.JLabel cars_panel_2_icon7;
    private javax.swing.JLabel cars_panel_2_icon8;
    private javax.swing.JLabel cars_panel_2_icon9;
    private javax.swing.JLabel cars_panel_2_name;
    private javax.swing.JLabel cars_panel_2_name1;
    private javax.swing.JLabel cars_panel_2_name10;
    private javax.swing.JLabel cars_panel_2_name2;
    private javax.swing.JLabel cars_panel_2_name3;
    private javax.swing.JLabel cars_panel_2_name4;
    private javax.swing.JLabel cars_panel_2_name5;
    private javax.swing.JLabel cars_panel_2_name6;
    private javax.swing.JLabel cars_panel_2_name7;
    private javax.swing.JLabel cars_panel_2_name8;
    private javax.swing.JLabel cars_panel_2_name9;
    private javax.swing.JLabel cars_panel_2_view_more;
    private javax.swing.JLabel cars_panel_2_view_more1;
    private javax.swing.JLabel cars_panel_2_view_more2;
    private javax.swing.JLabel cars_panel_2_view_more3;
    private javax.swing.JPanel cars_panel_3;
    private javax.swing.JPanel cars_panel_4;
    private javax.swing.JPanel cars_panel_5;
    private javax.swing.JPanel cars_panel_6;
    private javax.swing.JPanel cars_panel_7;
    private javax.swing.JPanel cars_panel_8;
    private javax.swing.JPanel cars_panel_9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel logout_label;
    private javax.swing.JLabel logout_textfield;
    private javax.swing.JLabel next_page_icon1;
    private javax.swing.JPanel next_page_panel1;
    private javax.swing.JLabel prev_page_icon1;
    private javax.swing.JPanel prev_page_panel1;
    // End of variables declaration//GEN-END:variables
}
